-- ============================================================
-- Polymarket Contrarian Bot — Initial Schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- Markets: active markets being monitored
CREATE TABLE IF NOT EXISTS markets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    polymarket_id TEXT UNIQUE NOT NULL,
    condition_id TEXT,
    question TEXT NOT NULL,
    category TEXT,
    end_date TIMESTAMP,

    yes_token_id TEXT,
    no_token_id TEXT,

    yes_price NUMERIC(6,4),
    no_price NUMERIC(6,4),

    volume_24h NUMERIC,
    liquidity NUMERIC,
    num_traders INTEGER,

    is_active BOOLEAN DEFAULT true,
    resolution TEXT, -- NULL | YES | NO

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_markets_active ON markets(is_active, end_date);
CREATE INDEX IF NOT EXISTS idx_markets_category ON markets(category);

-- Market snapshots: price history for divergence detection
CREATE TABLE IF NOT EXISTS market_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    market_id UUID REFERENCES markets(id),

    yes_price NUMERIC(6,4),
    no_price NUMERIC(6,4),
    volume_1h NUMERIC,
    spread NUMERIC(6,4),

    -- AI vs Humans divergence (built by us)
    ai_probability NUMERIC(6,4),
    human_probability NUMERIC(6,4),
    divergence_pct NUMERIC(6,4),

    -- Orderbook depth
    best_bid_yes NUMERIC(6,4),
    best_ask_yes NUMERIC(6,4),
    bid_depth_yes NUMERIC,
    ask_depth_yes NUMERIC,

    -- Whale activity (from PolymarketScan)
    whale_direction TEXT,       -- YES | NO | MIXED | NULL
    whale_trade_count INTEGER,
    whale_volume_usd NUMERIC,

    snapshot_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_snapshots_market_time ON market_snapshots(market_id, snapshot_at DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_divergence ON market_snapshots(divergence_pct) WHERE divergence_pct IS NOT NULL;

-- Signals: generated by the signal engine
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    market_id UUID REFERENCES markets(id),

    signal_type TEXT NOT NULL, -- CONTRARIAN_LONG | CONTRARIAN_SHORT | CONVERGENCE
    direction TEXT NOT NULL,   -- YES | NO
    confidence NUMERIC(5,4),

    price_at_signal NUMERIC(6,4),
    divergence_at_signal NUMERIC(6,4),
    volume_at_signal NUMERIC,

    divergence_score NUMERIC(5,2),
    momentum_score NUMERIC(5,2),
    smart_wallet_score NUMERIC(5,2),
    total_score NUMERIC(5,2),

    status TEXT DEFAULT 'ACTIVE', -- ACTIVE | EXECUTED | EXPIRED | CANCELLED

    created_at TIMESTAMP DEFAULT now(),
    expires_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_signals_active ON signals(status) WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_signals_market ON signals(market_id, created_at DESC);

-- Paper trades: simulated trading
CREATE TABLE IF NOT EXISTS paper_trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID REFERENCES signals(id),
    market_id UUID REFERENCES markets(id),

    direction TEXT NOT NULL,  -- YES | NO
    entry_price NUMERIC(6,4) NOT NULL,
    exit_price NUMERIC(6,4),
    shares NUMERIC NOT NULL,
    position_usd NUMERIC NOT NULL,

    pnl_usd NUMERIC,
    pnl_pct NUMERIC,

    opened_at TIMESTAMP DEFAULT now(),
    closed_at TIMESTAMP,
    close_reason TEXT, -- RESOLUTION | TRAILING_STOP | TAKE_PROFIT | TIMEOUT | CIRCUIT_BREAKER

    status TEXT DEFAULT 'OPEN' -- OPEN | CLOSED | CANCELLED
);

CREATE INDEX IF NOT EXISTS idx_trades_open ON paper_trades(status) WHERE status = 'OPEN';
CREATE INDEX IF NOT EXISTS idx_trades_pnl ON paper_trades(pnl_usd) WHERE status = 'CLOSED';

-- Portfolio state: single-row global state
CREATE TABLE IF NOT EXISTS portfolio_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    initial_capital NUMERIC NOT NULL DEFAULT 1000,
    current_capital NUMERIC NOT NULL DEFAULT 1000,
    total_pnl NUMERIC DEFAULT 0,
    total_pnl_pct NUMERIC DEFAULT 0,

    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    win_rate NUMERIC(5,4) DEFAULT 0,

    max_drawdown NUMERIC DEFAULT 0,
    sharpe_ratio NUMERIC,

    consecutive_losses INTEGER DEFAULT 0,
    is_circuit_broken BOOLEAN DEFAULT false,
    circuit_broken_until TIMESTAMP,

    open_positions INTEGER DEFAULT 0,
    max_open_positions INTEGER DEFAULT 5,

    updated_at TIMESTAMP DEFAULT now()
);

-- Watched wallets: smart money / bot tracking
CREATE TABLE IF NOT EXISTS watched_wallets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_address TEXT UNIQUE NOT NULL,

    label TEXT,
    tier TEXT DEFAULT 'B',          -- S | A | B
    wallet_type TEXT DEFAULT 'UNKNOWN', -- BOT | HUMAN | SMART_HUMAN | UNKNOWN
    category_specialty TEXT,

    win_rate NUMERIC(5,4),
    total_pnl NUMERIC,
    total_trades INTEGER,
    avg_position_size NUMERIC,

    is_active BOOLEAN DEFAULT true,
    freshness_score NUMERIC(5,4) DEFAULT 1.0,
    last_trade_at TIMESTAMP,

    source TEXT, -- polymarketscan | manual | discovered
    discovered_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallets_active_tier ON watched_wallets(is_active, tier);
CREATE INDEX IF NOT EXISTS idx_wallets_type ON watched_wallets(wallet_type);

-- ============================================================
-- Seed: initial portfolio state row
-- ============================================================
INSERT INTO portfolio_state (initial_capital, current_capital)
VALUES (1000, 1000)
ON CONFLICT DO NOTHING;
